### ISSUE TITLE
Error in `find` when playing web streams

### ISSUE THREAD

**Issue by albocc** [vehk/mpdnotify#6]
When `mpd` is playing web streams (e.g. via HTTP), the `find` command will fail since it can't find "/home/myuser/music/http://....".

Therefore there should be a check, if the currently playing "song" is actually a URL and not a file. If it's a URL, it should skip searching locally for a cover.

**Comment by albocc** [comment]
Thanks for the quick response! 

But why exit the whole script, if the directory does not exist? I think it's fine to still display a notification, just like if there is a song without cover art playing. What do you think?

Something like this:

```
@@ -51,12 +51,12 @@ song="$(mpc current -f "$T_FORMAT")"
 # Art directory
 art="$MUSIC_DIR/${file%/*}"
 
-# bail if the art directory does not exist (mpd is playing a stream, etc)
-[[ ! -d $art ]] && exit 1
-
-# find every file that matches IMG_REG set the first matching file to be the
-# cover.
-cover="$(find "$art/" -maxdepth 1 -type f | egrep -i -m1 "$IMG_REG")"
+# skip if the art directory does not exist (mpd is playing a stream, etc)
+if [[ -d $art ]]; then
+    # find every file that matches IMG_REG set the first matching file to be the
+    # cover.
+    cover="$(find "$art/" -maxdepth 1 -type f | egrep -i -m1 "$IMG_REG")"
+fi
 
 # when no cover is found, use DEFAULT_ART as cover
 cover="${cover:=$DEFAULT_ART}"
```

**Comment by vehk** [comment]
Sure, that makes more sense. I'm not actively using this script anymore, and I wasn't thinking clearly about it. If you want to, you can open a pull request, otherwise I'll make the change myself.
